### PR TITLE
Fix showing border when switching to an empty space

### PR DESCRIPTION
**Pull request by NTT123**
When I switch to an empty space, it keeps drawing the border of currently focused window even though we're now in a different space.

Also, when all windows are closed, the border is till there.

### CODE REVIEW

**Comment by koekeishiya** [comment]
> When I switch to an empty space, it keeps drawing the border of currently focused window even though we're now in a different space.

Unable to reproduce any of this. These issue was resolved in https://github.com/koekeishiya/chunkwm/issues/145 https://github.com/koekeishiya/chunkwm/issues/194 https://github.com/koekeishiya/chunkwm/issues/197 https://github.com/koekeishiya/chunkwm/issues/191

**Comment by crisidev** [comment]
I can reproduce this. It happens to me as well.

**Comment by koekeishiya** [comment]
I'm not claiming there aren't any problems, but I'm not able to reproduce any given the pretext above.
I also don't recall having any issues with the focused border in my usage.

If you could elaborate on whats steps are taken to reproduce your behaviour. Does this involve floating windows, multiple monitors. What settings have you defined for the border plugin etc.
Also just to verify that the border.so plugin loaded by chunkwm is the latest version, you can check in the logs which plugin details it yields.

A lot of things that may seem clear may actually depend on several other instances happening, because the AX API is complete garbage.

A border window persisting from one desktop to another desktop is simply not possible. If this is happening, that is a bug in the Cocoa window toolkit API or some personal-config setting, as we do NOT specify `NSWindowCollectionBehaviorCanJoinAllSpaces`. (We use `NSWindowCollectionBehaviorDefault`.)  

There is absolutely no reason why merging the border into the tiling plugin would resolve anything. They can both freely access the required information and events regardless.

**Comment by koekeishiya** [comment]
short gif demonstrating how it works for me:
```
 - open window
 - close window
 - close window
 - open window
 - close window
 - open window
 - switch to empty space
 - switch back
 - close window
```

border

**Comment by NTT123** [comment]
My bad for lack of details. I use 1 monitor with  5 virtual space. When I switch from a focused window to an empty space, using ctrl - left, the border is still there in the empty space.

**Comment by justfielding** [comment]
I also experience this issue. Here are some screenshots of what we are seeing.

The first screenshot is on virtual space 2 with the window on the top right focused (indicated by the purple border :neckbeard:). 
screen shot 2017-11-01 at 8 36 56 am

Simply switching to workspace 4 takes me there willy nilly as expected, but it seems the border plugin hasn't been clued in fully of the space change and maybe doesn't redraw it's border (removing focused border) or something is keeping the border visible from the previous space until a new window is focused.
screen shot 2017-11-01 at 8 37 03 am

**Comment by koekeishiya** [comment]
@justfielding The issue you described used to be a thing about a month or two ago, and I could reproduce it back then. It was a rather annoying issue, but I can no longer reproduce it on master, as shown in the gif i posted above.

I feel like the border plugin you guys are running at not the latest version, or there is some system-individual setting that changes the behaviour of some of the constants that we supply to the Cocoa framework.

Can you reproduce #191 ? (Is the border frame statically fixed when you are mid-space transitions, or does it slide along with the rest of the windows).

If you run chunkwm with logging enabled, it will print the version of the plugin border as it is loaded during startup.

**Comment by crisidev** [comment]
I am using this border plugin
PluginName 'Border'
PluginVersion '0.2.9'

I can reproduce the same behaviour @justfielding has with two monitors.

**Comment by koekeishiya** [comment]
> I can reproduce the same behaviour @justfielding has with two monitors.

I realize I also forgot to specify that I was running a triple monitor setup during my testing to produc ethe gif above, although the space (desktop) switch happens and everything happens on the same monitor.

@crisidev Would you mind compiling both chunkwm and the border plugin from source, and run it from a terminal with a fresh config (the sample config ?) using the `-c /path/to/config` argument. 

I really cannot reproduce this no matter what I try.

**Comment by koekeishiya** [comment]
Just to clarify, the reason this is fishy, is that the border window technically is not allowed to join ANY other space than the one it was created in

> A border window persisting from one desktop to another desktop is simply not possible. If this is happening, that is a bug in the Cocoa window toolkit API or some personal-config setting, as we do NOT specify NSWindowCollectionBehaviorCanJoinAllSpaces. (We use NSWindowCollectionBehaviorDefault.)

**Comment by crisidev** [comment]
@koekeishiya I have tried with a fresh compiled chunkwm, without brew plugins and with default config from the repo and it still happens.

**Comment by koekeishiya** [comment]
@crisidev I just did the same and it all works just fine... This is ridiculous..

I'm curious as to how #191 looks for you then, as this was resolved by relying on the same fix that would resolve the "border persisting on space change" issue.

**Comment by crisidev** [comment]
#191 is not happening to me. I use mission control driven by skhd to switch desktop, but the border does not show.

I have disabled transparency and checked reduced motions to avoid effects and also when re-enabling them the border is not shown during transition between desks.

I don't have high sierra yet. Do you think maybe that can be the issue (I don't think so)..

**Comment by koekeishiya** [comment]
> I don't have high sierra yet. Do you think maybe that can be the issue (I don't think so)..

All this was working just fine for me back on Sierra as well. Note that I already solved these issues back in early August. (Apparently there are cases where this did not actually seem to be solved for everyone ???).

I just fail to comprehend how the existing border from space 1, is visible on space 2, given only a "switch space" action being performed. The only way I can achieve that effect is to edit the border.mm file and replace `NSWindowCollectionBehaviorDefault` with `NSWindowCollectionBehaviorCanJoinAllSpaces` and recompile.

No idea how I can even start to debug this.

**Comment by koekeishiya** [comment]
Do people still have this problem, and if yes, do the changes in this PR fix it?
I still have not been able to reproduce this personally :/

**Comment by crisidev** [comment]
Yes, @NTT123 branch completely fixes the issue for me. Can this be merged?

**Comment by koekeishiya** [comment]
@crisidev 

Can you see if the latest master fixes the issue where a border would persist *through space change* ?

**Comment by crisidev** [comment]
Nice!! Latest master fixes the issue for me. No more rogue borders! Thanks a lot.

**Comment by koekeishiya** [comment]
@crisidev 

> Also, when all windows are closed, the border is till there.

 Does it also fix this issue ? If so, I'll consider this solved.

**Comment by koekeishiya** [comment]
So I'm trying some incremental fixes one by one to see what effects they have, cause the changes in this PR (might fix the problem), but I'd like to understand why, as they don't really make sense to me.

**Comment by crisidev** [comment]
Just tested https://github.com/koekeishiya/chunkwm/commit/7bf9004f4b2427e3a6402d9e160e25d774ba35f7

The problem is still there :( I'll continue testing your changes as they come.

**Comment by crisidev** [comment]
Wanna hear something funny? Last commit works for me. I don't see the borders anymore when I switch to an empty desktop.

**Comment by koekeishiya** [comment]
The problem I have with the latest commit is:

Setup: Have space1 with a single (terminal) window.
            Have space2 which is completely empty.

Steps:
On space1, start chunkwm manually inside the terminal window; notice border is drawn.
Switch to space2 using gesture (goto next space)

Notice border does disappear properly.

Switch back to space1, border is not drawn on terminal, although it does get focused properly.

**Comment by crisidev** [comment]
When I go back to space1, the border is there and the focus is handled properly.

**Comment by koekeishiya** [comment]
This feels like a very race-conditiony kind of issue, but I don't immediately see where.

**Comment by koekeishiya** [comment]
@crisidev 

The latest commit works perfect for me now.

Can you try to verify both of these when you have time:

> When I switch to an empty space, it keeps drawing the border of currently focused window even though we're now in a different space.

> Also, when all windows are closed, the border is till there.


Thanks :)

**Comment by crisidev** [comment]
I'll try in half an hour! Thanks as usual

**Comment by crisidev** [comment]
Just compiled and tried https://github.com/koekeishiya/chunkwm/commit/0312d62fa2fd70a5926e4c33abb5307d77621e3a and unfortunately the phantom border is back :(

**Comment by koekeishiya** [comment]
If this last one doesn't work, I'm kinda out of ideas..

**Comment by crisidev** [comment]
YES! This one did it. I will test it a little bit more for corner cases, but so far so good.

**Comment by koekeishiya** [comment]
Great, I'll be doing a new release in a bit then

**Comment by crisidev** [comment]
Ok. I'll change brew as soon as you release

**Comment by koekeishiya** [comment]
tag v0.3.3 is available now.

**Pull request closed without merging**
