### PR TITLE
Allow chunkc to change border color

### PR DESCRIPTION
**Pull request by darvelo**
I don't actually recommend this be merged.. I just use this feature a lot in `kwm` and wanted to express my support for its implementation in some other way than a request. This is quick and dirty and C/C++ are not my strong languages (ex. I got an error trying to refactor `Border` into a shared var in an `.h` file and did not succeed 😄).

I can now set the border color in `.khdrc` with:
`khd mode tree on_enter CHUNKC_SOCKET=5151 chunkc bordercolor 0xddfabd2f`

Working on this did show me an interesting implementation detail of `chunkwm`, namely: `chunkc` uses a [fallback port](https://github.com/koekeishiya/chunkwm/blob/fb6476f126d8e5f13154b1258cc1e513ed8ae6e2/src/chunkc/chunkc.c#L14) which defaults to the tiling plugin's port. How should this work when there are multiple plugins running their own listeners?

### CODE REVIEW

**Comment by koekeishiya** [comment]
> Working on this did show me an interesting implementation detail of chunkwm, namely: chunkc uses a fallback port which defaults to the tiling plugin's port. How should this work when there are multiple plugins running their own listeners?

See #57 

Quite a lof of challenges to be solved still, but I'd like to find a good solution as well.
I haven't really had the time to think more about it.

**Comment by darvelo** [comment]
Agreed. :) Now that I have this border stuff working, I can feel comfortable dropping `kwm` and using/testing `chunkwm` while the proper solution is worked out. Thanks for your work on both projects.

**Comment by synthetiv** [comment]
Thank you, @darvelo, for working this out, even if it's only a temporary solution.

For anyone else who wants to try this, I had trouble getting the on_enter config line to work as written above due to the – I ended up having to use `env` in the command too, like this:

```
khd mode tree on_enter env CHUNKC_SOCKET=5151 chunkc bordercolor 0xddffffff
```

**Comment by koekeishiya** [comment]
implemented on master, command is `chunkc border::color 0xAARRGGBB`

**Pull request closed without merging**
